# Default: 24
# Range: 4 ~ 64
wandInteractionDistance = 24
# Default: 0.0
# Range: 0.0 ~ 2.0
playerCastingDelayFactor = 0.0
# Default: 3
# Range: 1 ~ 16
ritualRange = 3

[materials]
	# Default: 64
	# Range: 1 ~ 1000
	crystalOfFlameRequirement = 64
	# Default: 64
	# Range: 1 ~ 1000
	crystalOfWinterstormRequirement = 64

[pop_fruit]
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	popFruitExplosionChanceOnEaten = 0.1
	# Default: 0.35
	# Range: 0.0 ~ 2.0
	popFruitExplosionDamageFactor = 0.35
	# Default: 0.05
	# Range: 0.0 ~ 1.0
	popFruitBonemealGrowChance = 0.05
	# Default: 100
	# Range: 10 ~ 1000
	popFruitNaturalGrowRarity = 100
	# Default: 3
	# Range: 0 ~ 100
	popFruitBiomeGrowFactor = 3
	# Default: 1
	# Range: 0 ~ 10
	popFruitAdjacentCrystalBoost = 1
